services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /opt/base
    environment:
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
      UV_CACHE_DIR: /opt/base/.uv-cache
      VIRTUAL_ENV: /opt/base/.venv
      PATH: /opt/base/.venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
